# The main config file for your Jekyll template

# Site settings
title: AstroDeep               # used for the html title of every page
desc: >
  Website of the AstroDeep ANR cosmology project which aims at using 
  Baysian neural networks for weak gravitational lensing analyses.

url: https://astrodeep.net  # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: contact@astrodeep.net
phone: +33 1 57 27 61 87
author: The AstroDeep team
# twitter_username: clenemt
gitlab_username: astrodeep

# Put your ga tracking code below
# google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Projects
    url: /projects/
    desc: Current projects
  - title: People
    url: /people/
    desc: The AstroDeep team
  # - title: Articles
    # url: /articles/
    # desc: Publications from AstroDeep members
  - title: Jobs
    url: /jobs/
    desc: Job offers from student internship to postdocs and engineers
  - title: Contact
    url: /contact/
    desc: How to reach us

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

